/// Flutter icons CustomCardIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomCardIcon
///      fonts:
///       - asset: fonts/CustomCardIcon.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class CustomCardIcon {
  CustomCardIcon._();

  static const _kFontFam = 'CustomCardIcon';
  static const _kFontPkg = null;

  static const IconData picture =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
